api_platform:
    title: Cinema Reservation API
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header